# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tfx/proto/orchestration/executable_spec.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tfx.proto.orchestration import placeholder_pb2 as tfx_dot_proto_dot_orchestration_dot_placeholder__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-tfx/proto/orchestration/executable_spec.proto\x12!tfx.orchestration.executable_spec\x1a)tfx/proto/orchestration/placeholder.proto\"D\n\x19PythonClassExecutableSpec\x12\x12\n\nclass_path\x18\x01 \x01(\t\x12\x13\n\x0b\x65xtra_flags\x18\x02 \x03(\t\"\xe3\x01\n\x12\x42\x65\x61mExecutableSpec\x12Z\n\x14python_executor_spec\x18\x01 \x01(\x0b\x32<.tfx.orchestration.executable_spec.PythonClassExecutableSpec\x12\x1e\n\x12\x62\x65\x61m_pipeline_args\x18\x02 \x03(\tB\x02\x18\x01\x12Q\n\x1f\x62\x65\x61m_pipeline_args_placeholders\x18\x03 \x03(\x0b\x32(.tfx.orchestration.PlaceholderExpression\"\x9c\x01\n\x17\x43ontainerExecutableSpec\x12\r\n\x05image\x18\x01 \x01(\t\x12:\n\x08\x63ommands\x18\x02 \x03(\x0b\x32(.tfx.orchestration.PlaceholderExpression\x12\x36\n\x04\x61rgs\x18\x03 \x03(\x0b\x32(.tfx.orchestration.PlaceholderExpressionb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tfx.proto.orchestration.executable_spec_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BEAMEXECUTABLESPEC.fields_by_name['beam_pipeline_args']._options = None
  _BEAMEXECUTABLESPEC.fields_by_name['beam_pipeline_args']._serialized_options = b'\030\001'
  _PYTHONCLASSEXECUTABLESPEC._serialized_start=127
  _PYTHONCLASSEXECUTABLESPEC._serialized_end=195
  _BEAMEXECUTABLESPEC._serialized_start=198
  _BEAMEXECUTABLESPEC._serialized_end=425
  _CONTAINEREXECUTABLESPEC._serialized_start=428
  _CONTAINEREXECUTABLESPEC._serialized_end=584
# @@protoc_insertion_point(module_scope)
