from typing import Any, Dict, Self

class QRIS:
    def __init__(self, path: str) -> None: ...
    @classmethod
    def from_str(cls, code: str) -> Self: ...
    @classmethod
    def from_dict(cls, data: Dict[int, Any]) -> Self: ...
    def save(self, path: str, width: str) -> None: ...
    def to_dict(self) -> Dict[int, Any]: ...
    def set_merchant_name(self, name: str) -> None: ...
    def set_merchant_city(self, city: str) -> None: ...
    def set_postal_code(self, code: str) -> None: ...
    def dumps(self) -> str: ...
