export enum EventCodes {
  REQ_APP_PING = 'REQ_APP_PING',
  REP_APP_PONG = 'REP_APP_PONG',
  REQ_APP_GET_CONFIG = 'REQ_APP_GET_CONFIG',
  REQ_APP_SET_CONFIG = 'REQ_APP_SET_CONFIG',
  REP_APP_CONFIG = 'REP_APP_CONFIG',
}
