# sleep
SLEEP_TIME = 1
LONG_SLEEP_TIME = 2
MONITOR_TIME_DEFAULT = "150"
# ENV VARIABLES
MONITOR_TIME_ENV = "MONITOR_TIME_ENV"
PROPHECY_PAT = "PROPHECY_PAT"

PROPHECY_URL = "PROPHECY_URL"

PROJECT_ID = "PROJECT_ID"
PIPELINE_ID = "PIPELINE_ID"
SEND_EMAIL = "SEND_EMAIL"
BRANCH = "BRANCH"
OUTPUT_DIR = "OUTPUT_DIR"

# EXCEL COLUMN NAMES
CATALOG_COL = "Target Catalog"
DB_COL = "Target Database"
TABLE_COL = "Target Table"
COLNAME_COL = "Column Name"
UPSTREAM_TRANSFORMATION_COL = "Upstream Lineage"
