def say_love(language, num_message):
    messages = {
        "tr": "Seni seviyorum",
        "az": "Mən səni sevirəm",
        "de": "Ich liebe dich",
        "en": "I love you",
        "fr": "Je t'aime",
        "es": "Te quiero",
        "it": "Ti amo",
        "nl": "Ik hou van jou",
        "pt": "Eu te amo",
        "ru": "Я тебя люблю",
        "zh": "我爱你",
        "ja": "愛してる",
        "ko": "사랑해",
        "ar": "أحبك",
        "hi": "मैं तुमसे प्यार करता हूँ",
        "th": "ฉันรักคุณ",
        "vi": "Anh yêu em",
        "fa": "من تو را دوست دارم",
        "sv": "Jag älskar dig",
        "no": "Jeg elsker deg",
        "da": "Jeg elsker dig",
        "cs": "Miluji tě",
        "el": "Σ' αγαπώ",
        "bs": "Volim te",
        "hr": "Volim te",
        "sq": "Të dua",
        "sk": "Milujem ťa",
        "sl": "Ljubim te",
        "tk": "Men seni söýýän",
        "bg": "Обичам те",
        "ky": "Мен сени сүйөм",
        "kk": "Мен сені сүйемін",
        "mn": "Би чамд хайртай",
        "uk": "Я тебе кохаю",
        "cy": "Rwy'n dy garu di",
        "tt": "Мин сине яратам",
        "sw": "Nakupenda",
        "ha": "Ina son ku",
        "am": "እኔ አንተን እወዳለሁ",
        "yo": "Mo nifẹ rẹ",
        "zu": "Ngiyakuthanda",
        "sn": "Ndinokuda",
        "xh": "Ndiyakuthanda"
    }
    message = messages.get(language, f"Sorry, 'I love you' is not available in '{language}' language code.")
    for _ in range(num_message):
      print(message, "\n")
    return "Done"