"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    The version of the OpenAPI document: 1.28
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import esi_client
from esi_client.model.get_universe_system_kills200_ok import GetUniverseSystemKills200Ok


class TestGetUniverseSystemKills200Ok(unittest.TestCase):
    """GetUniverseSystemKills200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUniverseSystemKills200Ok(self):
        """Test GetUniverseSystemKills200Ok"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetUniverseSystemKills200Ok()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
