"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    The version of the OpenAPI document: 1.28
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import esi_client
from esi_client.model.get_characters_character_id_opportunities200_ok import GetCharactersCharacterIdOpportunities200Ok


class TestGetCharactersCharacterIdOpportunities200Ok(unittest.TestCase):
    """GetCharactersCharacterIdOpportunities200Ok unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCharactersCharacterIdOpportunities200Ok(self):
        """Test GetCharactersCharacterIdOpportunities200Ok"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCharactersCharacterIdOpportunities200Ok()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
