"""
    EVE Swagger Interface

    An OpenAPI for EVE Online  # noqa: E501

    The version of the OpenAPI document: 1.28
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import esi_client
from esi_client.model.get_corporations_corporation_id_not_found import GetCorporationsCorporationIdNotFound


class TestGetCorporationsCorporationIdNotFound(unittest.TestCase):
    """GetCorporationsCorporationIdNotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetCorporationsCorporationIdNotFound(self):
        """Test GetCorporationsCorporationIdNotFound"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetCorporationsCorporationIdNotFound()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
