__author__ = "Jan Krupa"
__email__ = "jan.krupa@cesnet.cz"
__version__ = "1.2.6"
__description__ = "Synchronize data between Komora and NetBox. Copies Segment and Service Paths from Komora."
__name__ = "komora_service_path_plugin"
