# Generated by Django 2.2.24 on 2021-11-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_ep', '0057_actor_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='logo',
            field=models.CharField(blank=True, default='https://moncompte.energie-partagee.org/img/default_avatar_actor.svg', max_length=250, null=True, verbose_name='Logo'),
        ),
    ]
