# Generated by Django 4.2.7 on 2024-02-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_ep', '0074_alter_relatedactor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Visible sur la carte'),
        ),
    ]
