# Generated by Django 4.2.11 on 2024-08-26 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djangoldp_ep",
            "0131_citizenproject_created_at_citizenproject_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partnertype",
            name="partners",
        ),
        migrations.AlterField(
            model_name="partnerlink",
            name="link_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner_links",
                to="djangoldp_ep.partnerlinktype",
                verbose_name="Type de lien de partenariat",
            ),
        ),
        migrations.DeleteModel(
            name="Partner",
        ),
        migrations.DeleteModel(
            name="PartnerType",
        ),
    ]
