# Generated by Django 4.2.11 on 2024-11-25 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoldp_ep", "0135_remove_actor_adhesiondate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capitaldistribution",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Distribution du capital",
                "verbose_name_plural": "Distribution des capitaux",
            },
        ),
        migrations.AlterModelOptions(
            name="citizenproject",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Projet Citoyen",
                "verbose_name_plural": "Projets Citoyens",
            },
        ),
        migrations.AlterModelOptions(
            name="college",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Collège",
                "verbose_name_plural": "Collèges",
            },
        ),
        migrations.AlterModelOptions(
            name="collegeepa",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Collège EPA",
                "verbose_name_plural": "Collèges EPA",
            },
        ),
        migrations.AlterModelOptions(
            name="communicationprofile",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Profil de communication",
                "verbose_name_plural": "Profils de communication",
            },
        ),
        migrations.AlterModelOptions(
            name="contracttype",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Type de contrat",
                "verbose_name_plural": "Types de contrats",
            },
        ),
        migrations.AlterModelOptions(
            name="contribution",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Contribution",
                "verbose_name_plural": "Contributions",
            },
        ),
        migrations.AlterModelOptions(
            name="discount",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Réduction",
                "verbose_name_plural": "Réductions",
            },
        ),
        migrations.AlterModelOptions(
            name="earneddistinction",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Distinction des projets",
                "verbose_name_plural": "Distinctions des projets",
            },
        ),
        migrations.AlterModelOptions(
            name="energybuyer",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Acheteur d'énergie",
                "verbose_name_plural": "Acheteurs d'énergies",
            },
        ),
        migrations.AlterModelOptions(
            name="energytype",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Type d'énergie",
                "verbose_name_plural": "Types d'énergies",
            },
        ),
        migrations.AlterModelOptions(
            name="integrationstep",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Étapes d'intégration",
                "verbose_name_plural": "Étapes d'intégration",
            },
        ),
        migrations.AlterModelOptions(
            name="interventionzone",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Zone d'intervention",
                "verbose_name_plural": "Zones d'interventions",
            },
        ),
        migrations.AlterModelOptions(
            name="legalstructure",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Structure juridique",
                "verbose_name_plural": "Structures juridiques",
            },
        ),
        migrations.AlterModelOptions(
            name="partnerlinktype",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Type de lien de partenariat",
                "verbose_name_plural": "Types de liens de partenariat",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Méthode de paiement",
                "verbose_name_plural": "Méthodes de paiements",
            },
        ),
        migrations.AlterModelOptions(
            name="productionsite",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Site de production",
                "verbose_name_plural": "Sites de productions",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Profil",
                "verbose_name_plural": "Profils",
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Région",
                "verbose_name_plural": "Régions",
            },
        ),
        migrations.AlterModelOptions(
            name="regionalnetwork",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Réseau régional",
                "verbose_name_plural": "Réseaux régionaux",
            },
        ),
        migrations.AlterModelOptions(
            name="relatedactor",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
            },
        ),
        migrations.AlterModelOptions(
            name="shareholder",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Actionnaire",
                "verbose_name_plural": "Actionnaires",
            },
        ),
        migrations.AlterModelOptions(
            name="siteearneddistinction",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Distinction des sites",
                "verbose_name_plural": "Distinctions des sites",
            },
        ),
        migrations.AlterModelOptions(
            name="testimony",
            options={
                "default_permissions": {"delete", "view", "control", "add", "change"},
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
            },
        ),
        migrations.RenameField(
            model_name="actor",
            old_name="createdate",
            new_name="creation_date",
        ),
        migrations.RenameField(
            model_name="actor",
            old_name="updatedate",
            new_name="update_date",
        ),
        migrations.RenameField(
            model_name="citizenproject",
            old_name="created_at",
            new_name="creation_date",
        ),
        migrations.RenameField(
            model_name="citizenproject",
            old_name="updated_at",
            new_name="update_date",
        ),
        migrations.RenameField(
            model_name="contribution",
            old_name="createdate",
            new_name="creation_date",
        ),
        migrations.RenameField(
            model_name="contribution",
            old_name="updatedate",
            new_name="update_date",
        ),
        migrations.RenameField(
            model_name="energyproduction",
            old_name="created_at",
            new_name="creation_date",
        ),
        migrations.RenameField(
            model_name="energyproduction",
            old_name="updated_at",
            new_name="update_date",
        ),
        migrations.RenameField(
            model_name="productionsite",
            old_name="created_at",
            new_name="creation_date",
        ),
        migrations.RenameField(
            model_name="productionsite",
            old_name="updated_at",
            new_name="update_date",
        ),
        migrations.RenameField(
            model_name="relatedactor",
            old_name="createdate",
            new_name="creation_date",
        ),
        migrations.AddField(
            model_name="capitaldistribution",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="capitaldistribution",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="college",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="college",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="collegeepa",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="collegeepa",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="communicationprofile",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="communicationprofile",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="contracttype",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contracttype",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discount",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="earneddistinction",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="earneddistinction",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="energybuyer",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="energybuyer",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="energytype",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="energytype",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="integrationstep",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="integrationstep",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="interventionzone",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interventionzone",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="legalstructure",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legalstructure",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="partnerlink",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partnerlink",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="partnerlinktype",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partnerlinktype",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="regionalnetwork",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="regionalnetwork",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="relatedactor",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="shareholder",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shareholder",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="siteearneddistinction",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="siteearneddistinction",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AddField(
            model_name="testimony",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="testimony",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="citizenproject",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="college",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="collegeepa",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contracttype",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="earneddistinction",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="energybuyer",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="energytype",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="interventionzone",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="legalstructure",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="partnerlinktype",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="productionsite",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="regionalnetwork",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="siteearneddistinction",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="citizenproject",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="energyproduction",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="productionsite",
            name="update_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de dernière mise à jour"
            ),
        ),
        migrations.AlterModelOptions(
            name="capitaldistribution",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["-update_date"],
                "verbose_name": "Distribution du capital",
                "verbose_name_plural": "Distribution des capitaux",
            },
        ),
        migrations.AlterModelOptions(
            name="citizenproject",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Projet Citoyen",
                "verbose_name_plural": "Projets Citoyens",
            },
        ),
        migrations.AlterModelOptions(
            name="college",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Collège",
                "verbose_name_plural": "Collèges",
            },
        ),
        migrations.AlterModelOptions(
            name="collegeepa",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Collège EPA",
                "verbose_name_plural": "Collèges EPA",
            },
        ),
        migrations.AlterModelOptions(
            name="communicationprofile",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["-update_date"],
                "verbose_name": "Profil de communication",
                "verbose_name_plural": "Profils de communication",
            },
        ),
        migrations.AlterModelOptions(
            name="contracttype",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Type de contrat",
                "verbose_name_plural": "Types de contrats",
            },
        ),
        migrations.AlterModelOptions(
            name="contribution",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["-update_date"],
                "verbose_name": "Contribution",
                "verbose_name_plural": "Contributions",
            },
        ),
        migrations.AlterModelOptions(
            name="discount",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Réduction",
                "verbose_name_plural": "Réductions",
            },
        ),
        migrations.AlterModelOptions(
            name="earneddistinction",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Distinction des projets",
                "verbose_name_plural": "Distinctions des projets",
            },
        ),
        migrations.AlterModelOptions(
            name="energybuyer",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Acheteur d'énergie",
                "verbose_name_plural": "Acheteurs d'énergies",
            },
        ),
        migrations.AlterModelOptions(
            name="energytype",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Type d'énergie",
                "verbose_name_plural": "Types d'énergies",
            },
        ),
        migrations.AlterModelOptions(
            name="integrationstep",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["-update_date"],
                "verbose_name": "Étapes d'intégration",
                "verbose_name_plural": "Étapes d'intégration",
            },
        ),
        migrations.AlterModelOptions(
            name="interventionzone",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Zone d'intervention",
                "verbose_name_plural": "Zones d'interventions",
            },
        ),
        migrations.AlterModelOptions(
            name="legalstructure",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Structure juridique",
                "verbose_name_plural": "Structures juridiques",
            },
        ),
        migrations.AlterModelOptions(
            name="partnerlinktype",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Type de lien de partenariat",
                "verbose_name_plural": "Types de liens de partenariat",
            },
        ),
        migrations.AlterModelOptions(
            name="paymentmethod",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Méthode de paiement",
                "verbose_name_plural": "Méthodes de paiements",
            },
        ),
        migrations.AlterModelOptions(
            name="productionsite",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Site de production",
                "verbose_name_plural": "Sites de productions",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["-update_date"],
                "verbose_name": "Profil",
                "verbose_name_plural": "Profils",
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Région",
                "verbose_name_plural": "Régions",
            },
        ),
        migrations.AlterModelOptions(
            name="regionalnetwork",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Réseau régional",
                "verbose_name_plural": "Réseaux régionaux",
            },
        ),
        migrations.AlterModelOptions(
            name="relatedactor",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["-update_date"],
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
            },
        ),
        migrations.AlterModelOptions(
            name="shareholder",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["-update_date"],
                "verbose_name": "Actionnaire",
                "verbose_name_plural": "Actionnaires",
            },
        ),
        migrations.AlterModelOptions(
            name="siteearneddistinction",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["name"],
                "verbose_name": "Distinction des sites",
                "verbose_name_plural": "Distinctions des sites",
            },
        ),
        migrations.AlterModelOptions(
            name="testimony",
            options={
                "default_permissions": {"control", "delete", "add", "change", "view"},
                "ordering": ["-update_date"],
                "verbose_name": "Témoignage",
                "verbose_name_plural": "Témoignages",
            },
        ),
    ]
