import os
import typing as t
from types import SimpleNamespace

@t.overload
def set_output(name: str, value: str): ...
@t.overload
def set_output(data: dict): ...
@t.overload
def set_output(**kwargs): ...
@t.overload
def set_env(name: str, value: str): ...
@t.overload
def set_env(data: dict): ...
@t.overload
def set_env(**kwargs): ...
def add_path(path: str | os.PathLike): ...

class Summary(SimpleNamespace):
    @staticmethod
    def add(content: str, /, overwrite: bool = False): ...
    @staticmethod
    def clear(): ...
    def __call__(self, content: str, /, overwrite: bool = False): ...

summary = Summary
