
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-11T16:00:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c747dfa3bb713ddde37a81bd420aa0257aeb5df",
 "version": "1.8.96"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
