from setuptools import setup, find_packages

setup(
    name="ubicoders-vrobots",
    version="2.0.36",
    license="GPLv3",
    author="Elliot Lee",
    author_email="info@airnh.ca",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    url="https://github.com/ubicoders0/vrobots",
    keywords="ubicoders virtual robots",
    install_requires=[
        "websockets",
        "websocket-client",
        "numpy",
        "flatbuffers==23.5.26",
        "fastapi",
        "uvicorn",
        "asyncio",
        "requests",
        "psutil",
        "dash",
        "plotly",
        "colorama",
        "matplotlib",
        "pyqt5",
        "pyqtgraph",
        "pandas",
        "scipy",
        "ipython",
        "ipykernel",
        "jupyterlab",
        "ipympl",
    ],
)
