"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.8.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.api_resource_linked_resources import ApiResourceLinkedResources
from apideck.model.resource_status import ResourceStatus
globals()['ApiResourceLinkedResources'] = ApiResourceLinkedResources
globals()['ResourceStatus'] = ResourceStatus
from apideck.model.api_resource import ApiResource


class TestApiResource(unittest.TestCase):
    """ApiResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiResource(self):
        """Test ApiResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
