"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.8.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.connector_status import ConnectorStatus
from apideck.model.unified_api_id import UnifiedApiId
globals()['ConnectorStatus'] = ConnectorStatus
globals()['UnifiedApiId'] = UnifiedApiId
from apideck.model.connectors_filter import ConnectorsFilter


class TestConnectorsFilter(unittest.TestCase):
    """ConnectorsFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConnectorsFilter(self):
        """Test ConnectorsFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConnectorsFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
