
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-12-08T20:00:43-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8fd92fe5e6d49d6300b38f73ada6b662ecadc8a6",
 "version": "3.1.6.dev7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
