BUILDKIT_SECRET_MOUNT_PIP_CONF_ID = "pip.conf"
PIP_CONF_BUILDKIT_SECRET_MOUNT = (
    f"--mount=type=secret,id={BUILDKIT_SECRET_MOUNT_PIP_CONF_ID}"
)
PIP_CONF_SECRET_MOUNT_AS_ENV = (
    f"PIP_CONFIG_FILE=/run/secrets/{BUILDKIT_SECRET_MOUNT_PIP_CONF_ID}"
)
