#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Python 3.9

# @Time   : 2024/11/8 2:59
# @Author : 'Lou Zehua'
# @File   : tst_case.py 

import pandas as pd

from pandas import Timestamp


df_tst = pd.DataFrame([
    {'issue_number': 13432,
     'repo_id': 156018,
     'issue_author_id': 1809194,
     'issue_id': 2421413445,
     'create_ref_type': 'branch',
     'issue_comment_author_type': 'Bot',
     'pull_review_comment_author_type': 'Bot',
     'issue_title': '[QUESTION]zmalloc zlibc_free useless now?',
     'pull_review_state': 'approved',
     'commit_comment_author_type': 'Bot',
     'org_id': 1529926,
     'delete_pusher_type': 'deploy_key',
     'org_login': 'redis',
     'create_pusher_type': 'deploy_key',
     'release_author_type': 'Bot',
     'issue_author_login': 'ddatsh',
     'pull_requested_reviewer_type': 'Bot',
     'actor_login': 'ddatsh',
     'member_type': 'Bot',
     'pull_merged_by_type': 'Bot',
     'issue_created_at': Timestamp('2024-07-21 13:47:43'),
     'commit_comment_author_association': 'COLLABORATOR',
     'type': 'IssuesEvent',
     'pull_review_author_association': 'COLLABORATOR',
     'issue_author_type': 'User',
     'pull_review_comment_author_association': 'COLLABORATOR',
     'body': 'zlibc_free no use anymore?',
     'platform': 'GitHub',
     'fork_forkee_owner_type': 'Bot',
     'issue_updated_at': Timestamp('2024-07-21 13:47:43'),
     'created_at': Timestamp('2024-07-21 13:47:45'),
     'action': 'opened',
     'issue_comment_author_association': 'COLLABORATOR',
     'issue_author_association': 'NONE',
     'id': 40328385624,
     'repo_name': 'redis/redis',
     'actor_id': 1809194},
    {'platform': 'GitHub',
     'id': 39895864356,
     'type': 'IssuesEvent',
     'action': 'opened',
     'actor_id': 13570151,
     'actor_login': 'Orlion',
     'repo_id': 156018,
     'repo_name': 'redis/redis',
     'org_id': 1529926,
     'org_login': 'redis',
     'created_at': Timestamp('2024-07-05 09:36:18'),
     'issue_id': 2392238212,
     'issue_number': 13395,
     'issue_title': 'Should we reconsider making lazyfreeGetFreeEffort support string?',
     'body': 'I found that when deleting a large string through the unlink command, it is still deleted synchronously, which is very time-consuming and causes the main thread to be blocked, affecting subsequent requests.\r\n\r\nI encountered a real problem: we stored some large bitmaps in redis. When deleting such keys, the redis server CPU was high and accompanied by some timeout problems.\r\n\r\nI found that the lazyfreeGetFreeEffort function did not process the string type, and then I found this PR: [https://github.com/redis/redis/pull/8365](https://github.com/redis/redis/pull/8365)\r\n\r\nThe author of this PR also mentioned that when the string length is greater than a certain value, deletion is very time-consuming.\r\n\r\nSo, should we reconsider allowing the lazyfreeGetFreeEffort function to support large strings? \r\n\r\n#8365 ',
     'issue_labels.name': [],
     'issue_labels.color': [],
     'issue_labels.default': [],
     'issue_labels.description': [],
     'issue_author_id': 13570151,
     'issue_author_login': 'Orlion',
     'issue_author_type': 'User',
     'issue_author_association': 'NONE',
     'issue_assignee_id': 0,
     'issue_assignee_login': '',
     'issue_assignees.login': [],
     'issue_assignees.id': [],
     'issue_created_at': Timestamp('2024-07-05 09:36:17'),
     'issue_updated_at': Timestamp('2024-07-05 09:36:17'),
     'issue_comments': 0,
     'issue_closed_at': None,
     'issue_comment_id': 0,
     'issue_comment_created_at': None,
     'issue_comment_updated_at': None,
     'issue_comment_author_association': 'COLLABORATOR',
     'issue_comment_author_id': 0,
     'issue_comment_author_login': '',
     'issue_comment_author_type': 'Bot',
     'pull_commits': 0,
     'pull_additions': 0,
     'pull_deletions': 0,
     'pull_changed_files': 0,
     'pull_merged': 0,
     'pull_merge_commit_sha': '',
     'pull_merged_at': None,
     'pull_merged_by_id': 0,
     'pull_merged_by_login': '',
     'pull_merged_by_type': 'Bot',
     'pull_requested_reviewer_id': 0,
     'pull_requested_reviewer_login': '',
     'pull_requested_reviewer_type': 'Bot',
     'pull_review_comments': 0,
     'pull_base_ref': '',
     'pull_head_repo_id': 0,
     'pull_head_repo_name': '',
     'pull_head_ref': '',
     'repo_description': '',
     'repo_size': 0,
     'repo_stargazers_count': 0,
     'repo_forks_count': 0,
     'repo_language': '',
     'repo_has_issues': 0,
     'repo_has_projects': 0,
     'repo_has_downloads': 0,
     'repo_has_wiki': 0,
     'repo_has_pages': 0,
     'repo_license': '',
     'repo_default_branch': '',
     'repo_created_at': None,
     'repo_updated_at': None,
     'repo_pushed_at': None,
     'repo_topics.name': [],
     'pull_review_state': 'approved',
     'pull_review_author_association': 'COLLABORATOR',
     'pull_review_id': 0,
     'pull_review_comment_id': 0,
     'pull_review_comment_path': '',
     'pull_review_comment_position': '',
     'pull_review_comment_author_id': 0,
     'pull_review_comment_author_login': '',
     'pull_review_comment_author_type': 'Bot',
     'pull_review_comment_author_association': 'COLLABORATOR',
     'pull_review_comment_created_at': None,
     'pull_review_comment_updated_at': None,
     'push_id': 0,
     'push_size': 0,
     'push_distinct_size': 0,
     'push_ref': '',
     'push_head': '',
     'push_commits.name': [],
     'push_commits.email': [],
     'push_commits.message': [],
     'fork_forkee_id': 0,
     'fork_forkee_full_name': '',
     'fork_forkee_owner_id': 0,
     'fork_forkee_owner_login': '',
     'fork_forkee_owner_type': 'Bot',
     'delete_ref': '',
     'delete_ref_type': '',
     'delete_pusher_type': 'deploy_key',
     'create_ref': '',
     'create_ref_type': 'branch',
     'create_master_branch': '',
     'create_description': '',
     'create_pusher_type': 'deploy_key',
     'gollum_pages.page_name': [],
     'gollum_pages.title': [],
     'gollum_pages.action': [],
     'member_id': 0,
     'member_login': '',
     'member_type': 'Bot',
     'release_id': 0,
     'release_tag_name': '',
     'release_target_commitish': '',
     'release_name': '',
     'release_draft': 0,
     'release_author_id': 0,
     'release_author_login': '',
     'release_author_type': 'Bot',
     'release_prerelease': 0,
     'release_created_at': None,
     'release_published_at': None,
     'release_body': '',
     'release_assets.name': [],
     'release_assets.uploader_login': [],
     'release_assets.uploader_id': [],
     'release_assets.content_type': [],
     'release_assets.state': [],
     'release_assets.size': [],
     'release_assets.download_count': [],
     'commit_comment_id': 0,
     'commit_comment_author_id': 0,
     'commit_comment_author_login': '',
     'commit_comment_author_type': 'Bot',
     'commit_comment_author_association': 'COLLABORATOR',
     'commit_comment_path': '',
     'commit_comment_position': '',
     'commit_comment_line': '',
     'commit_comment_sha': '',
     'commit_comment_created_at': None,
     'commit_comment_updated_at': None}])
