# coding: utf-8

"""
    Schemantis API

    This the documentation for the Schemantis REST API.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class RetrieveMapPostRequestConfig(BaseModel):
    """
    RetrieveMapPostRequestConfig
    """  # noqa: E501

    prefix: Optional[StrictStr] = None
    suffix: Optional[StrictStr] = None
    source_label: Optional[StrictStr] = None
    intermediate_label: Optional[StrictStr] = None
    source_delimieter: Optional[StrictStr] = None
    intermediate_delimieter: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "prefix",
        "suffix",
        "source_label",
        "intermediate_label",
        "source_delimieter",
        "intermediate_delimieter",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetrieveMapPostRequestConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetrieveMapPostRequestConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "prefix": obj.get("prefix"),
                "suffix": obj.get("suffix"),
                "source_label": obj.get("source_label"),
                "intermediate_label": obj.get("intermediate_label"),
                "source_delimieter": obj.get("source_delimieter"),
                "intermediate_delimieter": obj.get("intermediate_delimieter"),
            }
        )
        return _obj
