# Generated by Django 2.2.19 on 2021-03-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoldp_ep', '0049_actor_updatedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='usercontact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='animateur régional contact'),
        ),
    ]
