# Generated by Django 4.2.7 on 2023-11-08 18:01

import djangoldp.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_ep', '0066_alter_actor_options_alter_college_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlid', djangoldp.fields.LDPUrlField(blank=True, null=True, unique=True)),
                ('is_backlink', models.BooleanField(default=False, help_text='set automatically to indicate the Model is a backlink')),
                ('allow_create_backlink', models.BooleanField(default=True, help_text='set to False to disable backlink creation after Model save')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de la réduction')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Montant de la réduction (%)')),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view', 'control'],
                'depth': 0,
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='villageoise',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='réseau des Centrales Villageoises'),
        ),
    ]
