# Generated by Django 4.2.11 on 2024-04-10 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "djangoldp_ep",
            "0089_rename_effective_commissionning_yearl_productionsite_effective_commissionning_year_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="admins",
            field=models.ManyToManyField(
                related_name="admin_regions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
