# Generated by Django 4.2.7 on 2024-04-23 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_ep', '0093_citizenproject_fundraising_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energybuyer',
            name='contract_type',
        ),
        migrations.AddField(
            model_name='energyproduction',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='djangoldp_ep.contracttype', verbose_name='Type de contrat'),
        ),
    ]
