# Generated by Django 4.2.7 on 2024-05-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_ep', '0100_remove_capitaldistribution_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitaldistribution',
            name='shareholder',
        ),
        migrations.AddField(
            model_name='capitaldistribution',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_distributions', to='djangoldp_ep.actor', verbose_name='Acteur'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='capital_distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='djangoldp_ep.capitaldistribution', verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='djangoldp_ep.actor', verbose_name='Acteur'),
        ),
    ]
