# Generated by Django 4.2.7 on 2024-05-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_ep', '0102_alter_shareholder_capital_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitaldistribution',
            name='individuals_capital_resident',
        ),
        migrations.RemoveField(
            model_name='capitaldistribution',
            name='other_funds_residents',
        ),
        migrations.RemoveField(
            model_name='capitaldistribution',
            name='neighboring_communities_capital',
        ),
        migrations.RemoveField(
            model_name='capitaldistribution',
            name='neighboring_communities_other_funds',
        ),
    ]
