# Generated by Django 4.2.11 on 2024-05-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "djangoldp_ep",
            "0110_alter_communicationprofile_long_description",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimony",
            name="author_picture",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Auteur: Photo"
            ),
        ),
        migrations.AlterField(
            model_name="testimony",
            name="content",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Contenu"
            ),
        ),
    ]
