TIMESERIES = "Timeseries"
WATER_LEVEL = "WaterLevel"

PUMP = "Pump"
PUMP_PREFIX = f"{PUMP}."

BOX_CULVERT = "BoxCulvert"
BOX_CULVERT_PREFIX = f"{BOX_CULVERT}."
BOX_CULVERT_OUT = f"Out.{BOX_CULVERT}."

CIRCULAR_CULVERT = "CircularCulvert"
CIRCULAR_CULVERT_PREFIX = f"{CIRCULAR_CULVERT}."
CIRCULAR_CULVERT_OUT = f"Out.{CIRCULAR_CULVERT}."

GATED_SPILLWAY = "GatedSpillway"
GATED_SPILLWAY_PREFIX = f"{GATED_SPILLWAY}."
GATED_SPILLWAY_OUT = f"Out.{GATED_SPILLWAY}."

FREE_SPILLWAY = "FreeSpillway"
FREE_SPILLWAY_PREFIX = f"{FREE_SPILLWAY}."
FREE_SPILLWAY_OUT = f"Out.{FREE_SPILLWAY}."

UNKNOWN_DISCHARGE = "UnknownDischarge"
UNKNOWN_DISCHARGE_PREFIX = f"{UNKNOWN_DISCHARGE}."

CAPACITY = "Capacity"
INTERVAL = "Interval"
DELTA = "Delta"

OUTFLOW = "Outflow"
INFLOW = "Inflow"

YEAR = "Year"
MONTH = "Month"
YEAR_MONTH = "YearMonth"
CAPACITY_HT = 'CapacityHT'