"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.8.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.delete_invoice_item_response import DeleteInvoiceItemResponse


class TestDeleteInvoiceItemResponse(unittest.TestCase):
    """DeleteInvoiceItemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteInvoiceItemResponse(self):
        """Test DeleteInvoiceItemResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteInvoiceItemResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
