"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.8.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.balance_sheet_reports import BalanceSheetReports
globals()['BalanceSheetReports'] = BalanceSheetReports
from apideck.model.balance_sheet import BalanceSheet


class TestBalanceSheet(unittest.TestCase):
    """BalanceSheet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalanceSheet(self):
        """Test BalanceSheet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BalanceSheet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
