"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.8.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.unified_id import UnifiedId
globals()['UnifiedId'] = UnifiedId
from apideck.model.create_tax_rate_response import CreateTaxRateResponse


class TestCreateTaxRateResponse(unittest.TestCase):
    """CreateTaxRateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTaxRateResponse(self):
        """Test CreateTaxRateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTaxRateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
