"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.8.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.webhook import Webhook
globals()['Webhook'] = Webhook
from apideck.model.create_webhook_response import CreateWebhookResponse


class TestCreateWebhookResponse(unittest.TestCase):
    """CreateWebhookResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateWebhookResponse(self):
        """Test CreateWebhookResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateWebhookResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
