"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.8.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.activity import Activity
from apideck.model.links import Links
from apideck.model.meta import Meta
globals()['Activity'] = Activity
globals()['Links'] = Links
globals()['Meta'] = Meta
from apideck.model.get_activities_response import GetActivitiesResponse


class TestGetActivitiesResponse(unittest.TestCase):
    """GetActivitiesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetActivitiesResponse(self):
        """Test GetActivitiesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetActivitiesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
