"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.8.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.profit_and_loss_records import ProfitAndLossRecords
globals()['ProfitAndLossRecords'] = ProfitAndLossRecords
from apideck.model.profit_and_loss_net_operating_income import ProfitAndLossNetOperatingIncome


class TestProfitAndLossNetOperatingIncome(unittest.TestCase):
    """ProfitAndLossNetOperatingIncome unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProfitAndLossNetOperatingIncome(self):
        """Test ProfitAndLossNetOperatingIncome"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProfitAndLossNetOperatingIncome()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
