"""
    Apideck

    The Apideck OpenAPI Spec: SDK Optimized  # noqa: E501

    The version of the OpenAPI document: 10.8.3
    Contact: support@apideck.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import apideck
from apideck.model.unified_id import UnifiedId
globals()['UnifiedId'] = UnifiedId
from apideck.model.delete_note_response import DeleteNoteResponse


class TestDeleteNoteResponse(unittest.TestCase):
    """DeleteNoteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeleteNoteResponse(self):
        """Test DeleteNoteResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DeleteNoteResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
