from .tensor_drpi import lr
from .tensor_drpi import dt
from .tensor_drpi import kms
from .tensor_drpi import ann
from .tensor_drpi import cnn
from .tensor_drpi import mnist
from .tensor_drpi import nlp
from .tensor_drpi import imgseg
from .tensor_drpi import ocr
from .tensor_drpi import fd
