MESSAGE_SLAVE_POS = 0
MESSAGE_TYPE_POS = 1

ONBOARD_DEVICE_ID = "NN9999"

PEMS_MASTER_CONGESTION_TIMEOUTS = 5
PEMS_MASTER_BLACKLIST_TIMEOUTS = 15
PEMS_SCHEDULER_CONGESTION_TIME_BASE = 2
PEMS_SCHEDULER_CONGESTION_TIME_MAX = 8
PEMS_SCHEDULER_BLACKLIST_TIME_BASE = 10
PEMS_SCHEDULER_BLACKLIST_TIME_MAX = 30